const sidebars = {

  // docs: [
  //   'noun'
  // ],

  // components: [
  //   'components/ImgText'
  // ]

  mySidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // generate sidebar from the docs folder (or versioned_docs/<version>)
    },
  ],

};

module.exports = sidebars;

