const sidebars = {

  // docs: [
  //   'noun'
  // ],

  // components: [
  //   'components/ImgText'
  // ]

  // mySidebar: [
  //   {
  //     type: 'autogenerated',
  //     dirName: '.', // generate sidebar from the docs folder (or versioned_docs/<version>)
  //   },
  // ],

  components: [
    {
      type: 'category',
      label: '组件',
      link: {
        type: 'generated-index',
        slug: '/components',
      },
      collapsed: true,
      items: [
        'components/ImgText'
      ]
    }
  ],

  docs: [
    {
      type: 'category',
      label: '文档',
      link: {
        type: 'generated-index',
        slug: '/document',
      },
      collapsed: true,
      items: [
        'noun'
      ]
    }
  ]

};

module.exports = sidebars;

